spring:
  application:
    name: saas-api
  datasource:
    url: jdbc:postgresql://localhost:5432/inventario_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true