spring:
  application:
    name: saas-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/inventario_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Estos bloques DEBEN estar al mismo nivel que 'spring:'
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: ${PORT:8080}

# Variable personalizada para tu WebConfig.java
app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}